---
- name: Add PPA Repository
  become: true
  apt_repository: repo=ppa:nginx/stable

- name: Update Apt
  become: true
  apt: update_cache=yes

- name: Install nginx
  become: true
  apt: pkg=nginx state=latest

- name: Add htpasswd configuration
  become: true
  template: src=htpasswd.tpl dest=/etc/nginx/conf/.htpasswd

- name: Change default nginx site
  become: true
  template: src=default.tpl dest=/etc/nginx/sites-available/default
  notify: restart nginx
