---
- name: Update Apt
  become: true
  apt: update_cache=yes

- name: Install System Packages
  become: true
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - python-software-properties
