---
- name: Add PPA Repository
  become: true
  apt_repository: repo=ppa:ondrej/php

- name: Update Apt
  become: true
  apt: update_cache=yes

- name: Install PHP 7.0
  become: true
  apt: name="{{ item }}" state=latest force=yes
  with_items:
    - php7.0-common
    - php7.0-fpm
    - php7.0-cli
    - php7.0-dev
    - php7.0-mbstring

- name: Start php7-fpm service
  service: name=php7.0-fpm enabled=yes state=started
